kind = "web"
previewPath = "/"
title = "Adil Studio"
version = "1.0.0"
id = "artifacts/adil-studio"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 20354

[services.development]
run = "pnpm --filter @workspace/adil-studio run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/adil-studio", "run", "build" ]
publicDir = "artifacts/adil-studio/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "20354"
BASE_PATH = "/"
